version: '3.1'
services:
    web:
        build: .
        image: md_backend
        ports:
            - "5001:5001"
        volumes:
            - .:/backend_sqlalchemy
        secrets:
            - FLASK_SECRET_KEY
            - MD_EMAIL_PASS
secrets:
    FLASK_SECRET_KEY:
        external: true
    MD_EMAIL_PASS:
        external: true
